### PR TITLE
update test branch

### PR DESCRIPTION
**Pull request by sonora**

### CODE REVIEW

**Comment by vshcherb** [comment]
@sonora will you be able to join our Telegram chat at lest OsmAnd Public chat - https://t.me/joinchat/F23xLkRF4r5Er262jSsHww

We would like to coordinate with you our translation efforts and some other ideas :-) I believe as we are growing in developer numbers chat could help sometimes cause email is very rarely used now

**Comment by sonora** [comment]
@vshcherb Victor, have you considered using Gitter? It was last year acquired by github, and integrates perfectly without extra software, userID,  permissions, yet another providing party,  etc.

I am personally challenging myself to keep my app and tool profile to the absolute minimum (also a necessity for some international travel), and have made it an adventure to find out what a reasonable minimum is in the inflation of tools we experience, particularly but not limited to IM.  :)

**Comment by vshcherb** [comment]
Yes let's try

**Comment by vshcherb** [comment]
Yes let's try https://gitter.im/OsmAndRoom/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Pull request merged**
