### PR TITLE
Try to support maxheight in routing.

### PR DESCRIPTION
**Pull request by aceman444**
I'd like to support maxheight limits for routing.

I'll try to put more files into this pull request. Let's see how it goes in this web interface :)

### CODE REVIEW

**Comment by aceman444** [comment]
Or should I just use the existing type="length" also for maxheight? The tag value syntax seems to be the same.

**Comment by aceman444** [comment]
I think that would be better to not duplicate code.

**Comment by vshcherb** [comment]
type = length is definitely enough, it would better called metric, but that is the same meaning

**Comment by aceman444** [comment]
OK, thanks.

**Pull request closed without merging**
