### PR TITLE
Fix route chart points drawing in OpenGL

### PR DESCRIPTION
**Pull request by cepprice**

### CODE REVIEW

**Comment by vshcherb** [comment]
Does it require updates in documentation for rendering layers?

**Comment by cepprice** [comment]
@vshcherb There is no info about order of route layer turn arrows or chart points in orders table. It should be?

**Comment by vshcherb** [comment]
Yes - it should be here https://docs.osmand.net/docs/technical/algorithms/map-rendering-layers

**Comment by cepprice** [comment]
@vshcherb  https://github.com/osmandapp/web/pull/63

**Pull request merged**
