### PR TITLE
[HH, BRP] Refactor makeStartEndPointsPrecise + prepareResult

### PR DESCRIPTION
**Pull request by RZR-UA**
TODO:

- [ ] check OsmAnd Anrdoid (Java/Native) + gpxApprox

This request fixes the sequence of calls:

1) `makeStartEndPointsPrecise()` - to make precision - **firstly**

2) `prepareResult()` - to calculate segments (time, distance) and load obf-regions - **finally**

`makePrecise` (boolean) used because `searchRouteInternalPrepare()` method might be called by `findGpxRouteSegment()` where `makeStartEndPointsPrecise()` is not required

iOS/native refactor: https://github.com/osmandapp/OsmAnd-core-legacy/pull/183

### CODE REVIEW

**Comment by RZR-UA** [comment]
https://github.com/osmandapp/OsmAnd-Issues/issues/2412

**Comment by ivanPyrohivskyi** [comment]
Generally I would be simplify code. Instead of adding many confused flags, need to return result from different branches (Java/C++/Java HH/C++ HH) without call makeStartEndPointsPrecise + prepareResult and do it in the end of calling.
For example in the method searchRoute we have three results in RouteCalcResult (Java/C++/C++ HH) and one HHNetworkRouteRes (Java HH). In the end of searchRoute we can call sequentially makeStartEndPointsPrecise + prepareResult (only for Java HH - separate).
For transfer to C++. For iOS have separate method RoutePlannerFrontEnd::searchRoute where we can also call makeStartEndPointsPrecise + prepareResult after call HH routing.

**Comment by RZR-UA** [comment]
Will be refactored as a new request soon. Kept as draft.

**Comment by RZR-UA** [comment]
closed

**Pull request closed without merging**
