### PR TITLE
 Fix SQLite open flags

### PR DESCRIPTION
**Pull request by jmakovicka**
app.openOrCreateDatabase expects flags from android.content.Context
which are completely different

### CODE REVIEW

**Comment by jmakovicka** [comment]
Hi,

I spotted this issue when trying to build Osmand for Android 24 API, wondering why Android keeps opening the database world readable. It turned out that the mode flags got misinterpreted.

**Comment by vshcherb** [comment]
Thanks

**Comment by crimean** [comment]
Unfortunately it causes error - http://pastebin.com/Uz5wj7yj
Rolled back.

**Comment by jmakovicka** [comment]
I will look into that. It's possible that the DB is not created when opened read-only, although CREATE_IF_NECESSARY is set.

The stack trace is from a clean install? Could you check if /data/data/net.osmand.plus/databases/poi_filters existed at the time of openDatabase call?

**Comment by crimean** [comment]
I tried CREATE_IF_NECESSARY without read-only flag - same thing.
This is from clean install. The poi_filters does not exist.

**Comment by jmakovicka** [comment]
I reproduced the bug on Marshallow. The problem is that the last subdir ("database") does not exist yet at 1st startup. So the proper fix is either
- adding mkdir in case the directory does not exist
- or giving up on readonly/read-write flag and opening always read-write using app.openOrCreateDatabase.

Also, I am not sure about the db == null error checks - according to docs, the db opening functions should either return a valid db handle, or throw SQLiteException.

**Pull request merged**
