### PR TITLE
Add hashtag with appname in notes #16489

### PR DESCRIPTION
**Pull request by deevroman**
https://github.com/osmandapp/OsmAnd/issues/16489

Example note: https://master.apis.dev.openstreetmap.org/note/46911

### CODE REVIEW

**Comment by vshcherb** [comment]
Is it a common practices for the apps? Or will it be just annoying trash as you can see in a conversation. 

Osm Notes is a conversation tool and not an editor, so it shouldn't matter which messenger do you use

**Comment by deevroman** [comment]
> Is it a common practices for the apps?

More like yes. The most popular editors actively [using](https://github.com/Zverik/every_door/pull/642#issuecomment-1735680249) notes (StreetComplete, MapsMe/OrganicMaps) add such information. And even the version + date of the maps used in the application. 

> Osm Notes is a conversation tool

In most cases, no. By my count, only 13% of notes have more than two comments (including the note itself). More than 5 is 1.6%, more than 10 is 0.01%. But note that such meta information is only added when the note is created. It certainly doesn't interfere with the discussion.

----

In Osmand's case, there are two other good reasons to add meta-information:

1. OsmAnd allows you to add anonymous notes. Often such notes make little sense and the author cannot be contacted. Having the name of the app, will add credibility.
2.  OsmAnd's maps can lag months behind the database. As the mappers who process the notes say, it is very useful to understand the state of the OSM database as seen by the user.

**Comment by mmd-osm** [comment]
In fact hashtags in notes are somewhat controversial, maybe check for yourself: https://github.com/openstreetmap/openstreetmap-website/issues/3932

**Comment by deevroman** [comment]
In this case, the only thing in dispute is how the metadata about the application should look (with or without a hashtag). 

The main argument in https://github.com/openstreetmap/openstreetmap-website/issues/3932 is whether the notes data model should be changed. Something tells me that there will be no changes in the near future... And until there are no changes, we can only use the text of the note.

**Pull request merged**
