### PR TITLE
Put Version info under About item

### PR DESCRIPTION
**Pull request by sonora**

### CODE REVIEW

**Comment by sonora** [comment]
Hi Dmytro, my thinking is the following:
1. It is customary in software to always find the exact installed version under "About".
2. Our "What's new" articles more coarsely refer to the _major release_ (and which one that is is stated in the article headline), so the exact version code is less needed under "What's new" .

Can you agree?

**Comment by vshcherb** [comment]
Not 100% sure...

**Comment by vshcherb** [comment]
This button is about company not about version.

**Comment by vshcherb** [comment]
Then we will have 2 versions. About OsmAnd 4.6 and What's new in 4.6.

They are both logical places but they duplicate. You are right About OsmAnd doesn't speak about product but speaks about Company or Project which will be version independent

**Pull request closed without merging**
