### PR TITLE
#9783 Fix broken app theme icon

### PR DESCRIPTION
**Pull request by AlexSyt**

### CODE REVIEW

**Comment by AlexSyt** [comment]
@Chumva , @vshcherb , hi guys :)
I participate in Hacktoberfest 2020 and I'd like to contribute to OsmAnd. Could you please label my pull requests as hacktoberfest-accepted if they work for you?
Thanks 😊

**Comment by AlexSyt** [comment]
@vshcherb , thanks!)
Could you add the "hacktoberfest-accepted" label so this PR also counts as my participation in Hacktoberfest?

**Comment by Chumva** [comment]
@AlexSyt I have added a label, please check if this pr is counted in Hacktoberfest.

**Comment by AlexSyt** [comment]
@Chumva , yep, it worked, thanks)
I'll see you in another PRs)

**Pull request merged**
