### PR TITLE
fastlane images, optimized with optipng

### PR DESCRIPTION
**Pull request by PanderMusubi**

### CODE REVIEW

**Comment by mikehgentry** [comment]
Image 02 has a typo - "you" should be "your"

**Comment by vshcherb** [comment]
@PanderMusubi  is it fine to store it here https://github.com/osmandapp/Osmand-misc ? This repository is already quite huge to store resources - same folder fastline is fine

**Comment by PanderMusubi** [comment]
Yes of course

**Comment by vshcherb** [comment]
Great looking forward! We will update screenshots with the most recent version and different translations

**Comment by shuvashish76** [comment]
@vshcherb
But as Izzy mentioned [here](https://github.com/osmandapp/OsmAnd/issues/7437#issuecomment-578325416): _They are in a separate repo, they won't show up e.g. at F-Droid, which would look for Fastlane data in the source repo (which would be here)._

So [those files](https://github.com/osmandapp/OsmAnd-misc/tree/master/fastlane/metadata/android) are laying there with no use to F-Droid. Would you rather consider including metadata here?

**Pull request closed without merging**
