### PR TITLE
distanceMeasurement_5 is an updated version of distanceMeasurement_4 (re...

### PR DESCRIPTION
**Pull request by michc**
distanceMeasurement_5 is an updated version of distanceMeasurement_4 (replaces it) which enhances the DistanceCalculator plugin.
    
    This release is based on Osmand master dated 27Feb14.
    
    In addition to distanceMeasurement_4:
    
    1. Fix loss of text notes linked to a gpx point when it is dragged to new location.
    2. Added MagnificationButtonsPlugin to provide separate screen magnification buttons, on screen display of zomm and magnification levels and separate selection menus for directly setting zoom and magnification.
    This plugin can be removed by omitting the MagnificationButtonPlugin,java file and removing the line in OsmandPlugin.java/initPlugins that installs the plugin.

The following modifications to the current DistanceCalculatorPlugin are provided:

1. Text size magnification.
2. Point and track magnification.
3. Small change to measurement origin icon to differentiate end of track (needed for subtrack and partial length display).
4. Add text box magnification linked to map magnification function.
5. Add planning point selection area size modification function.
6. Fix bug in GPX file saving: hangs if no tracks folder has been previously created.
7. Add editable notes to gpx/planning points.
8. Add selectable highlighting ofgpx/planning points with notes.
9. Add list, select and display function for all gpx/planning points with notes.
10. Add separate screen magnification buttons that can be enabled/hidden with option to select specific magnification from long click context menu.
11. When Magnification buttons are visible, change long press on map zoom buttons to provide selection menu for any desired zoom level.

### CODE REVIEW

**Comment by michc** [comment]
I have the latest version synched to V2.1.0 if you are interested. Drag and
drop editing of GPX track points, including insertion/deletion of points;
addition of notes to any GPX point (current version on Play Store does not
have usable notes). These should have been included more than a year ago

**Comment by vshcherb** [comment]
We still plan to change how we edit the track and even more to put that separate action the drawer. We hope it will be done in 2.3, but it is not clear. Mainly the changes will be related to context menu and not to drag/drop functionality. Addition of notes and points information, I'm not sure we dropped, I've thought we finally enabled it. Anyway the measurement plugin as itself, will be left and instead we will be working on fully GPX editor.

I think it will be interested for us if you share some screenshots and open new pull-request, though I can't promise that we merge it 1 to 1. I think it is very valuable and other people could build OsmAnd with your extension (unfortunately proper extension mechanism is not developed in OsmAnd via external dex-classes). 

Thanks!

**Comment by michc** [comment]
The note functionality is currently useless. You can not enter any data,
instead some useless parameter is shown (speed? + ?) that can not be
edited. I think it was abandoned in the middle of implementation. Also the
delete last point added does not work.

There are many different uses for a GPX editor but my original interest was
the planning aspect (hence Planning and Measurement). The "plans" I refer
to are manually created tracks that do not necessarily have simple
mathematical logic in determining the path taken. The path is created based
on the desire to travel to specific locations of interest and/or using
specific streets, etc. The sort of thing you do when sight seeing on foot
in a town. Shortest distance and speed have no bearing on the path
selected. Way points could be used but become clumsy when trying to choose
a path down alleyways, markets and streets of interest. An editor that can
move, add and delete points is essentiial.

I looked at the possibility of making the application fully extensible by
externally provided plugins but came to the conclusion that defining an API
was too difficult, mainly because the structure of the application was not
stable and was changing substantially in every release. Until/unless the
framework is stable it will be difficult to write plugins. The design must
be based on the concept that external components can interact with the
critical elements.

Drag and drop is simple and I have used it in my version without any
problems for 4 years. The biggest problem is related to screen size and
point selection radius. A large finger on a small screen can select several
points but making the selection area user changeable addresses this problem.

As I have other functionality in my branch I only merge (locally) with the
main branch every 6 - 12 months. I can provide a pull request to release
V2.1 but the changes even since then have continued very rapidly. I can
post screen shot on the User forum and can provide a fully functional apk
(including other functionality) to an upload server or dropbox.

**Comment by michc** [comment]
It appears that I do not have sufficient privileges to create new topics on
the Osmand Google pages

**Comment by vshcherb** [comment]
I don't think I blocked anyone at all. And I see newcomers create lots of new topics. Weird...

**Comment by michc** [comment]
It worked again after logging out and back in.

**Pull request closed without merging**
