### PR TITLE
Get back maxRouteLength for RouteTestingTest (required for tests 49,63)

### PR DESCRIPTION
**Pull request by RZR-UA**
This reverts commit 6ce98f8e074a5247843676d5738ff028803d569d.

### CODE REVIEW

**Comment by RZR-UA** [comment]
https://github.com/osmandapp/OsmAnd/issues/21424

**Comment by vshcherb** [comment]
Usually it's unnecessary if we can specify which segments are not allowed cause distance is highly dependent on first/last segment which might be added sometimes and logic check behind, so distance fluctuates over time where geometry coudln't

**Comment by RZR-UA** [comment]
When we do min/max check, exact distance value is not important and fluctuation over time is OK.

Just check the old issue:

https://github.com/osmandapp/OsmAnd/issues/18093

https://www.openstreetmap.org/way/508244839

In both routes (with/without the bug) the way 508244839 is present and exact segment is present too.

We could check an absence of other segments, but currently we do not have this feature in tests.

A presence check exist:

```
"expectedResults": {
  "4692930": "3"
}
```

An absence check as it could be implemented:

```
"expectedResults": {
  "4692930": "-1",
  "4692930": "-2",
  "4692930": "-3"
}
```

At the moment, since removing of `maxRouteLength` broke tests 49 and 63, the `maxRouteLength` should have been restored for compatibility reasons.

**Comment by vshcherb** [comment]
I think adding non-present segments more important than length

**Comment by RZR-UA** [comment]
https://github.com/osmandapp/OsmAnd/pull/21503/files
https://github.com/osmandapp/OsmAnd-resources/pull/1164/files

**Pull request closed without merging**
