### PR TITLE
Fix #16662

### LINKED ISSUE #16662: Sorting tracks causes the application to crash
### Description
When specifying in sorting item nearest osmand crashes
<table style="width:100%">
  <tr>
<th> </th>
  </tr>
</table>  

```
Version  OsmAnd~ 4.4.0#14230mqta
11.03.2023 12:12:11
Apk Version : 4.4.0#14230mqta 4400
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeLo(TimSort.java:781)
	at java.util.TimSort.mergeAt(TimSort.java:518)
	at java.util.TimSort.mergeCollapse(TimSort.java:448)
	at java.util.TimSort.sort(TimSort.java:245)
	at java.util.Arrays.sort(Arrays.java:1495)
	at java.util.ArrayList.sort(ArrayList.java:1470)
	at java.util.Collections.sort(Collections.java:206)
	at net.osmand.plus.configmap.tracks.SelectedTracksHelper.sortTrackTab(SelectedTracksHelper.java:197)
	at net.osmand.plus.configmap.tracks.TracksFragment.setTracksSortMode(TracksFragment.java:369)
	at net.osmand.plus.configmap.tracks.SortByBottomSheet$SortModesAdapter.lambda$onBindViewHolder$0$net-osmand-plus-configmap-tracks-SortByBottomSheet$SortModesAdapter(SortByBottomSheet.java:107)
	at net.osmand.plus.configmap.tracks.SortByBottomSheet$SortModesAdapter$$ExternalSyntheticLambda0.onClick(Unknown Source:6)
	at android.view.View.performClick(View.java:7753)
	at android.view.View.performClickInternal(View.java:7730)
	at android.view.View.access$3700(View.java:861)
	at android.view.View$PerformClick.run(View.java:29136)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8105)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

```

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14230mqta, Дата выпуска: 2023-03-11
Android version: 12
Device model: poco f3

### PR DESCRIPTION
**Pull request by Chumva**

### CODE REVIEW

**Comment by sonora** [comment]
Vitaliy, the crash seems gone with this! But the sorting has flaws, see this section, sorting is "Nearest":

Screenshot_20230311-211933_OsmAnd~

Also, like before, the track 2016-11-29... has only 2 trkseg's with one point in each, and it  shows no blue distance value.

**Comment by sonora** [comment]
@Chumva PS: Looking at the code, it strikes me that the Comparator does not implement java.io.Serializable, I have a feeling that may help to simplify the sorting operation, but am not sure.

**Comment by sonora** [comment]
PS2: Also, the null checking code in in some places can be optimized in this fashion:
```
    if (id1 == null) {
        return id2 == null ? 0 : 1;
    }
    if (id2 == null) {
        return -1;
    }
    return id1.compareTo(id2);
```

**Comment by Chumva** [comment]
@sonora there was missing return, nearest sort should work fine now

**Comment by sonora** [comment]
Yes, I just noticed!

Are these obsolete?
https://github.com/osmandapp/OsmAnd/blob/1bdc1fd74022e974c7f6e36c320088eaeca257d2/OsmAnd/src/net/osmand/plus/configmap/tracks/TracksComparator.java#L126-L127

**Comment by Chumva** [comment]
Partially, we can pass them as arguments in compareNearestItems

**Comment by sonora** [comment]
Exactly.

How about https://github.com/osmandapp/OsmAnd/pull/16668#issuecomment-1465135644, probably saves some CPU cycles in several places?

**Comment by Chumva** [comment]
Yes, we can make https://github.com/osmandapp/OsmAnd/pull/16668#issuecomment-1465135644, but I am not sure if it will have much influence on performance

**Pull request merged**
