### PR TITLE
tighten parseLength() again

### PR DESCRIPTION
**Pull request by aceman444**
I wonder what the test for "-" does. There can't be any negative values in maxlength or maxheight.
It seems your version also accepts values like "1 km 1 km" (meaning 2km) which is invalid per the wiki, but probably shouldn't harm. I'm fine with that. But I think it also accepted "1 mile" and thinking it was 1meter. You can't just test unit.contains("m") as that would also match "mile", "cm", etc. That is not good so I tightened it a bit.

So I haven't compiled this again, please tell me if all the tests pass.

### CODE REVIEW

**Comment by aceman444** [comment]
What does the label mean? Can you build OsmAnd with the patch and say if it works and all the tests pass? It will be useful for the maxheight support in routing.

**Comment by aceman444** [comment]
Can you please look at the patch?

**Comment by vshcherb** [comment]
I don't really understand the change and I think the current solution works fine. May be it is good but it requires quite some investigation, last time it took quite a lot for that small feature to analyze

**Comment by aceman444** [comment]
OK, take your time:) I explained why the change is needed (what is wrong with current state) and also added more tests so it can be verified if the code works right.

**Comment by aceman444** [comment]
So what has changed? Why is the patch bad?

**Comment by vshcherb** [comment]
I added the test cases and they are all passing (https://github.com/osmandapp/Osmand/commit/c792360fdd4f8db7155375d4f4c5c09fe3ba9162) except few with bad value. So I don't see a reason to change code.

**Comment by aceman444** [comment]
Yes, because you do not test what happens on invalid values.

**Pull request closed without merging**
