### PR TITLE
Remove probably superfluous commas in strings.xml

### PR DESCRIPTION
**Pull request by aceman444**
Remove probably superfluous commas in strings.xml

### CODE REVIEW

**Comment by sonora** [comment]
http://www.getitwriteonline.com/archive/052709serialcomma.htm

**Comment by aceman444** [comment]
Interesting, thanks.

**Comment by aceman444** [comment]
But somebody has done this in strings for iOS version and it was accepted :)

**Comment by sonora** [comment]
Yeah, hard to keep things in sync, and I really hardly have enough time to maintain some consistency in our Android code ... :)

Fact remains that in English it is conventional (I think almost mandatory) to have the serial comma, while I am aware that is some other languages like e.g. German it is definitely the opposite.

**Pull request closed without merging**
