### PR TITLE
Update favorite_edit_dialog.xml

### PR DESCRIPTION
**Pull request by Edward17**
I propose to make some changes in Favourite edit dialog:
Delete unused LinearLayout and android:minLines="2", add ScrollView, other small fixes

### CODE REVIEW

**Comment by vshcherb** [comment]
Would be better to see screenshots. And I'm not sure minlines should be deleted because it shows multiline structure as it supposed to be for description

**Comment by Edward17** [comment]
@vshcherb , OK, android:minLines="2" can be kept on
> because it shows multiline structure

Why I propose to add ScrollView? In landscape orientation "Description" fielв is not visible and there isn't any ability to scroll down and fill this field:

screenshot

A display isn't small: 4,3 ", 720x1280 px

**Comment by vshcherb** [comment]
Yes good idea. Please put minLines=2 and we will merge immediately.

**Comment by Edward17** [comment]
I have added minLines=2.

**Comment by Edward17** [comment]
Thanks!

**Pull request merged**
