### PR TITLE
Add 'Postcode' to address search

### PR DESCRIPTION
**Pull request by keunes**
After some searching on the website I figured out that search based on postcode *is* possible. Rather than giving explanation on the website, it's more convenient to novice users to just print the info in the search screen.

### CODE REVIEW

**Comment by vshcherb** [comment]
Unfortunately it doesn't fit UI

**Comment by keunes** [comment]
Doesn't fit as in? (is it a matter of being ugly or really not fitting? I suspect it's the former as to me there seems enough space to accommodate the word postcode, which is just one letterspace longer than 'building')

**Comment by vshcherb** [comment]
Doesn't fit in the search address screen on the left column

**Comment by noci2012** [comment]
Zipcode?

**Comment by vshcherb** [comment]
The issue will be anyway present with translation, I think we need to add postcode in the text box hint when you enter the city, but I'm afraid it is already there?

**Comment by keunes** [comment]
> I think we need to add postcode in the text box hint when you enter the city, but I'm afraid it is already there?

That's a good one. Currently when the 'City' text field is empty, it displays 'CHOOSE CITY' we could append ... OR POSTCODE (or replace OR with / if needed)
Seems there's enough space there, and it would help a lot as well.

**Pull request closed without merging**
