### PR TITLE
Small changes in structure of address- and coordinates search window

### PR DESCRIPTION
**Pull request by Edward17**
With this changes User Interface will be more logical.

### CODE REVIEW

**Comment by vshcherb** [comment]
Can you please provide screenshots to understand the change.

**Comment by Edward17** [comment]
Here:

**Comment by vshcherb** [comment]
My concern is only that keyboard can hide Latitude on small screens and I believe I saw it couple of times. For the rest I'm fine, let's see if Dmitriy can say something.

**Comment by vshcherb** [comment]
Unfortunately no action was made since pull request and right now it's going to deprecate with new search.

**Pull request closed without merging**
