### PR TITLE
Fix #12481 Turn lanes are shown as through lanes in lane overview

### LINKED ISSUE #12481: Turn lanes are shown as through lanes in lane overview
### Description

OsmAnd does not always show the correct lanes in the lane overview.

In the example shown below, when driving on the road from north west to south east, the road is splitting into two left turn lanes and two through lanes before the junction at the bottom of the picture:

image

(OSM link: https://www.openstreetmap.org/edit?editor=id#map=18/55.37221/10.44506)

The two left lanes are mapped as a single way in OSM with `lanes=2` and `turn=left`. The two through lanes are mapped as a single way with `lanes=2`. This looks correct to me, but as seen below, OsmAnd shows 4 through lanes instead:

Screenshot_20210814-163456

On a side note, the "turn slightly right" instruction (see top-left corner of the screen) seems wrong as well, given that I was to drive straight ahead.

### Your Environment
OsmAnd Version: 4.0.5
Android/iOS version: 10

**Maps used (online or offline):** Online

### PR DESCRIPTION
**Pull request by Dima-1**

### CODE REVIEW

**Comment by sonora** [comment]
This gives me:

> > Task :OsmAnd-java:test
> 
> net.osmand.router.RouteResultPreparationTest > testLanes[58: 49.Turn lanes are shown as through lanes in lane overview https://github.com/osmandapp/OsmAnd/issues/12481] FAILED
>     org.junit.ComparisonFailure at RouteResultPreparationTest.java:112
> 
> 143 tests completed, 1 failed
> 
> > Task :OsmAnd-java:test FAILED

**Comment by sonora** [comment]
Was working on the audio focus topic, using https://builder.osmand.net:8080/view/All/job/OsmAnd-design/ to build.

This somehow got on the middle - what do I need to do?

**Comment by vshcherb** [comment]
Probably try it again

**Comment by vshcherb** [comment]
Or merge master to your branch.

**Comment by sonora** [comment]
Yeah, that's it - thanks. I was somehow missing that last commit from master.

**Pull request merged**
