### PR TITLE
Fix #16751 Accidental change of map rotation in "North is up (fixed)"…

### LINKED ISSUE #16751: Accidental change of map rotation
I believe that changing the dead zone for initiating the manual map rotation from 30 deg to just 5 deg here https://github.com/osmandapp/OsmAnd/pull/16746 increases the risk of accidentally  changing to manual map rotation when just pinch-zooming. Manual rotation is actually a rather rare use case for the majority of users...

### PR DESCRIPTION
**Pull request by sonora**
… mode

### CODE REVIEW

**Comment by vshcherb** [comment]
This is default mode and I would say it should be the mode where angle threshold should definitely be 5 so user can freely rotate without a glitch

**Comment by sonora** [comment]
Shall we perhaps amend the PR to apply for the 2D mode only?

The crux is exactly that
- "North is up" is the default mode every casual user gets (and many never intend to change it),
- and most users use OsmAnd simply like a map for orienteering purposes, expect North to be up,
- and the use case of twisting the map to view the landscape under a certain angle is comparatively rare, and possibly mostly needed in the 3D mode?

In addition,
- accidental map rotation can go unnoticed,
- or if noticed, some "normal" users are not aware how to reset it,
- or get tired of having to manually reset the orientation after many zoom operations.

I am really convinced by the feedback we see in issues, I get in person, and my own personal use last week that we have a cause for action here.

**Comment by vshcherb** [comment]
This what need to be precisely tested first

Map gestures sensitivity in north up fixed:
- Rotating - 5 degrees
- Zooming - 0.15z
- Zooming & Rotating - 15 degrees, zoom > 0.3, 30 degrees zoom > 2

**Comment by vshcherb** [comment]
Second we could speak about the sensitivity numbers but need to be precise

**Comment by vshcherb** [comment]
Btw we re still fixing to have exact constants in the code, so please don't hurry with code

**Comment by vshcherb** [comment]
Btw we re still fixing to have exact constants in the code, so please don't hurry with code, testing environment and numbers are much more important

**Pull request closed without merging**
