### PR TITLE
Add CONTRIBUTING.md and INSTALL.md 

### LINKED ISSUE #5357: consider adding CONTRIBUTING.md file with build instructions
I checked [FAQ](http://osmand.net/help-online) and there was no answer there.

I attempted to find build instructions and managed to discover

- https://github.com/osmandapp/OsmAnd-core#installation-on-ubuntu (for 14.04 LTS)
- http://osmand.net/help/TechnicalArticles.html#Install_Development_Environment that has different instructions
- https://code.google.com/archive/p/osmand/wikis/InstallDevelopmentEnvironment.wiki and https://code.google.com/archive/p/osmand/wikis/GradleCommandLineBuildEnvironment.wiki with yet another set of instructions

It is unclear which, if any, set of instructions is preferable to build Osmand app from source.

### PR DESCRIPTION
**Pull request by bagage**
Fix #5357.

Similarly to #9703, this is based on Angular's files. 
  
:construction: work in progress

### CODE REVIEW

**Comment by bagage** [comment]
For now I thought it would have been enough to use NDK 17b, clone project with `git-repo` and use `cd android && ./gradlew OsmAnd:installFreedevLegacyX86Debug` but it fails with various errors like:

> make: *** No rule to make target `jni/../../../core-legacy/targets/android/jpeg/../../../externals/skia/upstream.patched/third_party/externals/libjpeg-turbo/jsimd_none.c', needed by `obj/local/x86/objs/osmand_jpeg/__/__/__/externals/skia/upstream.patched/third_party/externals/libjpeg-turbo/jsimd_none.o'.  Stop.

Are you using a different set of instructions @vshcherb @Chumva @max-klaus?

**Comment by vshcherb** [comment]
Nope, so far it compiles fine on the build server https://builder.osmand.net:8080/view/OsmAnd%20Builds/job/OsmAnd-main/

**Comment by bagage** [comment]
Thanks for the pointer @vshcherb! It looks like my Android SDK was somewhat corrupted and I managed to build OsmAnd but without the NDK yet. I'll open a separate issue for that anyway.

**Comment by bagage** [comment]
Pull request is ready to be reviewed :).

**Comment by vshcherb** [comment]
I thinik we're not going to have contirbuting or install separate files, we have already partial information there https://github.com/osmandapp/osmandapp.github.io/blob/master/website/help/faq.html, so we're going to keep it in 1 place

**Comment by bagage** [comment]
@vshcherb build instructions should be located within source code repository and not on a *user* FAQ. Having to browse a website to get instructions is not really standard, plus you won't be able to read them if you are offline (in that case you won't be able to build anyway, but at least you can get a glance to the instructions).

Instead I suggest to migrate FAQ build instructions in `INSTALL.md` - where developers expect such instructions to be found.

**Pull request closed without merging**
