### PR TITLE
modes for BRouter

### PR DESCRIPTION
**Pull request by vodie**
set the right modes for BRouter with the new Aplication Profiles

### CODE REVIEW

**Comment by EssBee59** [comment]
Hello,

I tested this morning the Osmand Version 3.4.0 (beta) with Brouter 1.5.2:
- I think, my osmand configuration is ok (new config-Format of Osmand using an own profile with Navigation type = Brouter). 
- But something works not as expected: The Routing is not calculated with my Brouter-profile (fastbike), it Looks like a car profile…

Using the same Brouter with osmand 3.2.7 is ok
Yesterday, I got (after several minutes)  osmand 3.4.0 running with a previous Brouter Version

Any Idee what is wrong?
  Regards
Ess Bee

**Comment by vodie** [comment]
Hello Ess Bee,

have you set the right base profile for your own profile. For BRouter bike mode you need cycling as your base profile.

Regards Volker

**Comment by EssBee59** [comment]
Hello,
yes, the serviceconfig.dat is correct.
I am now sure, the brouter is using the first profile of his list (
car-fat.brf by me).
I replaced the car-fast.brf with my own profile and the routing is now ok.
Probably a problem in brouter, as till now the brouter profile was only
selected in itself?
Regards and thank for help

vodie <notifications@github.com> schrieb am Fr., 5. Juli 2019, 11:50:

**Comment by vodie** [comment]
Hello Ess Bee,
this is not a problem with BRouter. The base profile in Osmand set the routing mode for BRouter. If your base profile of your own profile in Osmand is set to cycling BRouter should use the bike profiles.
Regards Volker

**Comment by EssBee59** [comment]
Hello Vodie,
Thank for your help first!
AS Brouter is OK with Osmand 3.2.7, I agree, the Problem is probably in Osmand 3.4.0.
(I am in contact with the Osmand support)

But the behaviour is strange, can you have a look at my last test?
 
I created in Osmand a profile as follow:
Base profile: Fahrrad (bike)
Navigation Type: Brouter (Offline)

In the Brouter I selected my "fastbike-verylowtraffic" profile and (to be sure) assigned it for the 6 modes!!!
Result in serviceconfig.dat:
bicycle_fast fastbike-verylowtraffic
bicycle_short fastbike-verylowtraffic
foot_fast fastbike-verylowtraffic
foot_short fastbike-verylowtraffic
motorcar_fast fastbike-verylowtraffic
motorcar_short fastbike-verylowtraffic

Why is Brouter using "car-fast" in that Situation?

**Comment by vshcherb** [comment]
I see in the code
```
	bpars.putDoubleArray("lats", lats);
		bpars.putDoubleArray("lons", lons);
		bpars.putString("fast", params.fast ? "1" : "0");
		bpars.putString("v", mode);
```
So I guess mode should be selected correctly. @vodie please let us know if you can double check, otherwise we can create another issue and try to debug it.

**Comment by EssBee59** [comment]
Sory, my Expertise is limited:
I supose "mode" should be something as "car", "bike" or "hiking", and it is probably not set correctly in this beta release of Osmand?
(the Brouter-interface has changed in Osmand 3.4.0 beta)

I Forward now to Osmand support

Regards

**Comment by vodie** [comment]
@vshcherb the mode for BRouter is set by Osmand for cycling if params.mode.isDerivedRoutingFrom(ApplicationMode.BICYCLE) is true. If this doesn't work at least the car mode would be activated. But the modes seem not to be the problem, because even if he sets all modes in BRouter to his bike profile he don't get the right route. I suspect BRouter is not called. 
@EssBee59 how do you know it's the car-fast profile? Please create an empty "debug.txt" file in your brouter folder and start a routing request with Osmand. BRouter will write log messages in this file (if BRouter is called at all) which contains the used profile.

Regards Volker

**Comment by EssBee59** [comment]
Hi,
The Situation is very confusing:
3 days ago, after the osmand update to 3.4.0, the wrong routing occured 3 or 4 times, after 10 minutes it was ok. 
yesterday, after installing Brouter 1.5.2, I had the same Problem again, and 3 Hours later I replaced the car-fast with my profile (thinking, the bad profile is called in Brouter)..
..after this step the first Routing test was successfull!!??
Sorry: This morning, I have no error and  the debug confirms the call.
(with an exception: when I use a track, and configure Osmand to calculate the route from my Position to the start Point of the track, Brouter is not called… but it seems an other Problem)
I will test again and try to reproduce the error
Regards

**Comment by EssBee59** [comment]
Hello Volker,
I installed Brouter 1.5.3 today: No routing problems occured as last Friday, Osmand 3.4.0 remains stable…
So I tried to test the "Routing instructions":
In the past I only concentrated on the Routing calculation, and my profile was configured with
"assign   turnInstructionMode  0   "
The Navigation instructions (voice and the visual display of the TurnInstructions) was probaly generated by Osmand?
I tested today with Osmand+ 3.2.7 and Osmand 3.4.0 on Brouter 1.5.3:
-  I did not see differences between "assign   turnInstructionMode  0  " and "assign   turnInstructionMode  3 "
- visual display of the TurnInstructions was correct using Osmand+ 3.2.7
- visual display of the TurnInstructions was wrong using Osmand 3.4.0
(I think, Osmand 3.4.0 displays the turninstruction for the NEXT NEXT turn, not the NEXT turn!)
Can you please Forward by Need to the Right page?
Regards

**Comment by vodie** [comment]
Hallo Ess Bee,
if you set "assign turnInstructionMode 0" with Osmand there is no difference to "assign turnInstructionMode 3". Older Osmand versions don't make use of the additional data and Osmand 3.4.0 set the turnInstructionMode to Osmand if "assign turnInstructionMode 0" to get the travel time estimation and turn instructions.
You can activate the next turn in "Configure Screen" (Anzeige konfigurieren) for each application mode separately.

**Comment by EssBee59** [comment]
Hello Voker,
I retested today with Brouter 1.5.3 and the released osmand 3.4.2:
- The Route is calculated as awaited (on the map)
- The tun instuctions (voice and visual dssplay) are ok when assign turnInstructionMode 0
- With assign turnInstructionMode 3 (or  1) the turn instructions were NOT ok

(please lease let me know your test results, I make errors as every Body)
As the default  value for assign turnInstructionMode is 1, it could be confusing for users without experience or Knowledge of the profile Code.   
(I tested with my own profile, and I had same result with the Standard "trekking.brf")

**Comment by vodie** [comment]
Hello Ess Bee,

with turnInstructionMode 0 you get turn instructions generated by Osmand based on the geometry of the route. Maybe your BRouter profiles are old and without the parameters for hint generation or wrong parameters? For further help I need more information on what is not OK.

Regards Volker

**Comment by EssBee59** [comment]
Hello Volker,

I installed Brouter new from Google play (1.4.11)
With Osmand 3.4.2 I had the same Problems: The turn instructions (voice and display) are not ok when the turnInstructionMode is not set to 0.
I did not installed osmand new, perhaps is this the Problem.

**Comment by vodie** [comment]
In Brouter 1.4.x with intermediate Points there is bug in the turn instructions for Osmand. The current Google Play version is quite old. What is wrong with the instructions from BRouter?

**Comment by EssBee59** [comment]
I installed Brouter 1.5.3 and osmand 3.4.3 new and started a Long test (80 km fastbike).
I used an own profile with turnInstructionMode  1 (the "voice hint Generation" part is identical to trekking.brf" 
My first Problem, I awaited the same instruction as generated by osmand:
But Brouter generates less turn WP as osmand... This was confusing for me after monthes of Navigation with osmand. 
In most of the Situation, the turn WP of Brouter are reaching, but in 80 km I missed nearly 10 turn WP:

I had a look at the generated turn WP by using Brouter-web and turnInstructionMode 3: Brouter had not generated the missed turn WP.
(I can provide the gps files if you need, please give me a mail address for that)

I had also once the Situation that the turn WP was not spoken by osmand...

Last question:
Is it possible to configure the frequency of the "turn WP" in the profile?
If yes, could you provide a documentation?

Regards

**Comment by vodie** [comment]
BRouter generates much fewer hints than Osmand. If there are missing hints please open an issue on https://github.com/abrensch/brouter with brouter-web links to the sections with the missing instructions.
For the other BRouter related questions there is https://groups.google.com/forum/m/#!forum/osm-android-bikerouting.

**Comment by EssBee59** [comment]
Thank for the links:
I visited the Forums and found interesting tipps and documentation for the generation of the instructions:
I changed the following:

assign turnInstructionCatchingRange 2  (global)

assign priorityclassifier = 10  (way)

With the Change the number of instructions on my tour increased from 62 to 82...
AND I do not miss instructions any more!   

Before, with OSMAND, the number of instructions was much higher (200 till 300).
Brouter is better (especially in roundabout) and no unnecessary instructions are generated.

For me, it was important not to miss instructions, because I use in Osmand the feature "turn screen on/off", so the screen is most of the time off... fine for the Batterie, but bad if an instruction is missed
(instructions turn the screen on for N seconds)

regards

**Pull request merged**
