### PR TITLE
Remove round edges and strokes form map hud

### PR DESCRIPTION
**Pull request by codingjoe**
Hey there,

my first time here, kind of exiting. I've been using the app for a while now mostly for hiking. For that I always had some information displayed on the map overlay hud, like altitude and others.

That being said, the hud always looked like it was designed for one thing and then grew to become something bigger. I though a little redesign might be in order. I do have some more ideas, but I first wanted to figure out if you guys are even interested in me redesigning the UI a bit.

I removed the _90s_ stroke and round corners, centered the icons, made the light template hud translucent (the dark one already was) and made sure the pressed state color is the same for all button overlays.

I hope you like it, I added some screenshots.

Love the project, really great app!
-Joe

#### Dark mode
Screenshot_1572872809
Screenshot_1572872824

##### Dark mode (transparent)
Screenshot_1572872861
Screenshot_1572872875

#### Light mode
Screenshot_1572874089
Screenshot_1572874076

##### Light mode (transparent)
Screenshot_1572874017
Screenshot_1572874012

### CODE REVIEW

**Comment by jensMF** [comment]
I like it! :-)

**Comment by codingjoe** [comment]
> I like it! :-)

Glad to hear that! I'd actually like to redesign the whole navigation screen a little. There is a lot of information all over the screen. I'd like the navigation to be all like an EU/US blue/green highway sign and on the upper left side. All action buttons should stay on the lower end of the screen, close to the thumb, to make one hand interactions easier.

I figured, I start easy though, since I am new to this project form a development standpoint and my Java is a little rusty 😜 

What's the process. Is there a place where I should discuss my ideas first? Like a mailing list, GH issues, IRC? Otherwise, I'll just go ahead and doodle something :)

**Comment by ADepic** [comment]
https://github.com/osmandapp/Osmand/issues/5649

@codingjoe these were my observations about navigation in osmand (spoiler: it's awful and needs to be severely improved). Since you seem to be the only person who cares about improving the navigation screen, hopefully this is useful to you :) . 

P.s. why remove the rounded corners? Most material design buttons and other rectangles have _slightly_ rounded corners. The hard turn seems a bit crude, I don't see any hard in having _slightly_ rounded corners.

**Comment by codingjoe** [comment]
@codingjoe I removed the round corners, because it was technically not very feasible, since every element can be a button with a different on-click background color. It would need to be refactored a lot, to change that behavior and I did not want to introduce to big a change as a first contribtuion.

**Comment by TheAdventurer64** [comment]
@codingjoe Finally, someone who actually cares about the UI design of OSMAnd. Are you still working on this?

**Comment by codingjoe** [comment]
No it was done, but I can rebase it. I was just waiting for someone to review it.
I would consider working more on the UI of OSMAnd, but I wanted to keep my first contribution small to learn the ins and outs first.

**Comment by fhamborg** [comment]
Any news on this? If I see this correct this PR is still missing a review isn't it?

**Comment by codingjoe** [comment]
> Any news on this? If I see this correct this PR is still missing a review isn't it?

Yes, it seems so. I'd love to find someone for a review. I'd love to redo the entire hud, this was only meant as my first contribution, to learn the ropes.

**Comment by vshcherb** [comment]
@codingjoe this is unlikely will be merged as is. It's not a question of functionality but UI / UX related question. I think if it's really need to be merged into mainstream branch, it need to be considered as plugin functionality that will work via Package / Profile. It might not be easy to implement and require communication with dev team (via Telegram for example) but it will open the door for similar contributions.

**Comment by codingjoe** [comment]
> @codingjoe this is unlikely will be merged as is. It's not a question of functionality but UI / UX related question. I think if it's really need to be merged into mainstream branch, it need to be considered as plugin functionality that will work via Package / Profile. It might not be easy to implement and require communication with dev team (via Telegram for example) but it will open the door for similar contributions.

Thank you, @vshcherb, for your response and for pointing out the Telegram chat. I don't care much about the patch, it's a small change, I just wanted to propose to get to know the community and the development process a little better. But I presume there are better ways to do that. I will close the PR for now. One less thing to worry about.

**Pull request closed without merging**
