### PR TITLE
Added test for "Mo-Th 09:00-03:00, Fr-Sa 09:00-04:00; Su off". Not evaluated correctly. Related to #1154.

### PR DESCRIPTION
**Pull request by ypid**

### CODE REVIEW

**Comment by vshcherb** [comment]
testOpened("16.05.2015 03:59", hours, true); // FIXME: Wrong
I think this is correct
Fr-Sa 09:00-04:00 it stays that Saturday will be open till 4 o'clock, for me it is hard to image if I see 
Fr-Sa 09:00-04:00, Su off this, I would think other way

**Comment by ypid** [comment]
I am not sure if I understood you correctly. Please check on the [evaluation tool](http://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-Th%2009%3A00-03%3A00%2C%20Fr-Sa%2009%3A00-04%3A00%3B%20Su%20off&DATE=1431213240000&lat=48.7769&lon=9.1844&mode=0). Is the value evaluated there as you expect it?
2015-05-16 03:59 (Sa) should be open because of the rule: "Fr-Sa 09:00-04:00"

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/commit/5cd40baff32df901437ff2db48ba19287fd42563

**Comment by vshcherb** [comment]
Yes, it should be open. I didn't understand what is the failure I did only small change "," -> ';' , seemingly osmand doesn't parse ',' correctly I think in the following examples it should be just replaced with ';'.

Please submit other failing tests or point to any wrong test

**Comment by ypid** [comment]
> Please submit other failing tests or point to any wrong test

For starters, you can have a look at the test framework of opening_hours.js :smile:
https://github.com/ypid/opening_hours.js/blob/master/test.js

> [I intend to bundle the javascript library into a Java library (.jar) in the future. Would you consider using it then?](https://github.com/osmandapp/Osmand/issues/1154#issuecomment-100557718)

**Comment by vshcherb** [comment]
I never doubt to use something standard or specially purposed. I even think to start with it in iOS, though for existing solutions I have really strong criteria it shouldn't be worse by any meaning:
- I see js more powerful
- I'm not sure about performance, it could be critical because we have search POI that are opened, so the numbers of POI starts with 1K and this is on Android devices (!) of course we expect this to be quick
- It is used for maxspeed:conditional routing times and there it could even more critical, but I hope it is not used directly in routing

Current solution solves most of the opening times I know, new UI is made in a such a way that it shows original string even if it is wrong, the user could see the times. I see quite a big problem that OSM data is going to a format which user might not understand, which means that it should be specially formatted and so on.

So it is a hard choice, but if you could help us, you are welcome & we are ready to try it.

**Comment by vshcherb** [comment]
I would also think something JS -> Java automatic translation.

**Comment by ypid** [comment]
OK, good to hear that. It will probably take me some time before the Java library is ready and tested. I will keep you posted.
The performance question is an open question but it should work. Maybe some caching can reduce the performance problem.
An automatic translation of the JavaScript code into Java Code is [not practical/doable](https://stackoverflow.com/questions/10370384/how-to-convert-javascript-to-java).

**Pull request merged**
