### PR TITLE
Created draft of "BUILDING.md" file

### PR DESCRIPTION
**Pull request by skozyr**
It's hard to any documentation on building OsmAnd project from scratch.
I was able to find some legacy non relevant manuals at: 

* https://github.com/osmandapp/Osmand/issues/1386
* https://code.google.com/archive/p/osmand/wikis/InstallDevelopmentEnvironment.wiki
* https://code.google.com/p/osmand/wiki/GradleCommandLineBuildEnvironment

But technical section on osmand.net really helped me.
It's impossible to Google any instruction by search term "osmand build" or "osmand build android", so I think BUILDING.md file is needed for this project.

### CODE REVIEW

**Comment by vshcherb** [comment]
I think the document is outdated and doesn't reflect current status.

**Comment by sedot42** [comment]
@vshcherb Would you be interested in updating the document so it reflects current status? Or do you know anyone who might be?

**Comment by vshcherb** [comment]
I wouldn't mind though I don't know the current status in details, I can comment what's likely correct.

**Comment by byronigoe** [comment]
There are a few things I would like to improve in OsmAnd (e.g. better handling of GPX files with multiple tracks, support for KMZ files, using multiple colors for tracks, showing waypoints from current recording), and there appears to be a backlog of issues. If there were current/accurate/complete documentation about how to get started developing, I would be inclined to fix bugs, implement features, and submit PRs.

**Comment by vshcherb** [comment]
@byronigoe projects could be easily opened with Android Studio  and you only need to properly put git repositories in the right folders as mentioned here - https://github.com/osmandapp/OsmAnd-manifest/blob/master/commit.xml. 

If you are not Android Developer it might be quite difficult to find a right place where to introduce the changes, please check around if you understand project structure.

**Comment by vshcherb** [comment]
https://osmand.net/help-online/faq#dev-environment this is a properly updated documentation

**Pull request closed without merging**
