### PR TITLE
New Routing: Horsebackriding

### PR DESCRIPTION
**Pull request by derfuessl**
Translation of the parameters into German

### CODE REVIEW

**Comment by vshcherb** [comment]
@Chumva 
We also will need to make this routing  default to Horse riding profile

**Comment by derfuessl** [comment]
Can I help in any way?

**Comment by vshcherb** [comment]
Well new profile similar to motorbike should be created and routing should be assigned.

**Comment by vshcherb** [comment]
+ We need to add new Base profile for Horse riding (disabled by default)

**Comment by cepprice** [comment]
https://github.com/osmandapp/OsmAnd/pull/new/horse_riding

**Pull request merged**
