### PR TITLE
Patched Osmand icu4j to support Persian and Urdu #2019

### PR DESCRIPTION
**Pull request by AmZaf**
As mentioned by @sonora the commit d73f34d caused bloated apk. I have backported my changes to the original Osmand library so that the file size remains virtually unchanged and the issue #2019 gets resolved.

### CODE REVIEW

**Comment by vshcherb** [comment]
The only one place it is used is in the class Reshaper, is it possible to add a simple test in main method? So next time we know what is expected value.

**Comment by AmZaf** [comment]
Yes, it's possible. You mean like the one commented out for Hebrew?

**Comment by vshcherb** [comment]
Yes, I don't why I commented it out, but at least serves the purpose. More or less reasonable example of tests are here https://github.com/osmandapp/Osmand/blob/master/OsmAnd-java/src/net/osmand/util/OpeningHoursParser.java#L879

**Comment by AmZaf** [comment]
Here is a simple Arabic shaping test case:

	public static void main(String[] args) {
		String s = "گچ پژ نمکی باللغة العربي";
		String reshape = reshape(s);

		if(!reshape.equals("ﻲﺑﺮﻌﻟﺍ ﺔﻐﻠﻟﺎﺑ ﯽﮑﻤﻧ ﮋﭘ ﭻﮔ")) {
			throw new IllegalArgumentException("BUG!!!");
		}
	}

**Comment by AmZaf** [comment]
Why is there a size discrepency in the the displayed apk size? http://download.osmand.net/latest-night-build/

**Pull request merged**
