### PR TITLE
Fix accidental map rotation in "North is up" mode (#16836, #17086)

### PR DESCRIPTION
**Pull request by sonora**

### CODE REVIEW

**Comment by mnalis** [comment]
Thanks, I've [tried](https://github.com/mnalis/OsmAnd/actions/runs/5020936569) it quickly against recent `master`, and it seems to work as advertised:

https://github.com/osmandapp/OsmAnd/assets/156656/1c7d4865-23a4-491f-a72f-ef3e5844a4c3

**Comment by sonora** [comment]
You can set the threshold to anything you like in `NORTH_LOCK_ANGLE_THRESHOLD = 30;`, 30 degrees was the value we had used for many years.

**Comment by cyberman54** [comment]
Could we please merge this soon? The new UI behaviour is annoying, leads to permanent unwanted rotations of map in "North up fixed" mode.

**Comment by Boothy99** [comment]
Looks like an excellent solution that should keep everyone happy, thanks @sonora 👌

**Comment by vshcherb** [comment]
North up (fixed) mode should be removed as never existed in the app except the naming. I believe it should be Map Rotation lock which will apply to any rotated angle and could also prevent accidental map changes.

**Comment by vshcherb** [comment]
PR changes default behavior that locks rotation in default mode, it's unacceptable. 
We need to either change rotation algorithm (as we now will explore again) or create a way to lock mode and explain to the users

**Comment by cyberman54** [comment]
Why can't we just go back to the previous implementation? I never had a rotation UX problem with OSMand before. 

The current UX is very annoying. Do we really want to keep this for 6 months, until next regular release... ?

**Comment by vshcherb** [comment]
Previous implementation also had accidental map rotation and caused friction for map rotation

**Comment by mnalis** [comment]
People following this (including me :smile:) should try how 4.5.1beta behaves, as there have been changes, e.g. https://github.com/osmandapp/OsmAnd/issues/17086#issuecomment-1569285378

**Comment by Nine-Tailed** [comment]
now you can’t use gestures without irritation, they just broke what worked for years without any complaints.

**Pull request closed without merging**
